### ISSUE TITLE
OHBM Jupyter Notebooks

### ISSUE THREAD

**Issue by MCaviezel** [ghammad/pyActigraphy#10]
Hi Grégory,

I was at your software demonstration at the OHBM in Rome last week.
There you showed us an awesome Jupyter Notebook with even more features than described in your repository (e.g. signal filtering).
Would it be possible to make these notebooks you used at the demonstration public available?
This would be very helpful!
Thanks for your efforts and best regards,

Marco

**Comment by ghammad** [comment]
Hi @MCaviezel 

Sure. On the long term, the idea is to document all the functionalities of the package through notebooks. I'll come back to you once it is done.

Qucik question; by "filtering", I assume you talk about filtering out spurious activities. There will also be a notebook on filtering high frequency components (i.e. smoothing)

**Comment by ghammad** [comment]
List of available notebooks:

- [ ] Gentle introduction to pyActigraphy
- [ ] Rest-Activity rhythm variables (a.k.a non-parametric variables)
- [ ] Rest/Activity fragmentation via state transition probability
- [ ] Data cleaning (part 1: cleaning the start and the end of the recordings)
- [ ] Data cleaning (part 2: masking spurious inactivity periods)
- [ ] Visualise sleep diaries and compute summary statistics
- [ ] Data filtering (part 1: Fourier basis expansion)
- [ ] Data filtering (part 2: Spline interpolation)

I will update this list as soon as the notebooks are available.
In addition, more notebooks will be added in the near future.

**Comment by ghammad** [comment]
Hi all,

I just uploaded new notebooks to illustrate new features of the pyActigraphy package.

Happy actigraphying.

Grégory

**Comment by ghammad** [comment]
Hi all,

the official v1.0 release of pyActigraphy has just been made public. All the features mentioned above are documented in the Tutorial section of the online documentation: https://ghammad.github.io/pyActigraphy/tutorials.html

Happy actigraphing!

Greg
