### ISSUE TITLE
AX3 Reader

### ISSUE THREAD

**Issue by ghammad** [ghammad/pyActigraphy#11]
New feature: develop a reader for the OpenMovement AX device.

Documentation about the data format:
https://github.com/digitalinteraction/openmovement

Steps:

- [x] write a class for parsing the CWA binary file header
- [x] write a class for parsing the CWA binary file block
- [x] write a class CWA that reads binary file and creates a pyActigraphy object (base class: `BaseRaw`)

**Comment by nbeliy** [comment]
The actual implementation is too slow.
A typical file contains ~ 500000 blocks with ~140 samples (for AX3). It makes a serie of 70 millions of data (all in memory). DataFrame/Serie can (I hope manage it) but it manages the data append horribly.

I will experiment with possible solutions.

**Comment by ghammad** [comment]
The implementation of a reader able to handle the AX3 native format is postponed to the next major release.
