### ISSUE TITLE
Add support for different model of Actiwatch-L

### ISSUE THREAD

**Issue by deborabconstantino** [ghammad/pyActigraphy#123]
There are two patterns for the UUID recorded with the Actiwatch-L - one with a lowercase 'l' and one with a capital 'L'. Currently, pyActigraphy only supports files with the capital 'L' in the UUID.

Thank you,
Debora.

**Comment by ghammad** [comment]
Hello Debora.

Now fixed in v1.2.1.

Thank you for reporting this issue.

Closing now but feel free to re-open this issue if needed.

Best regards.

Greg
