### ISSUE TITLE
Read actilife data

### ISSUE THREAD

**Issue by loukasilias** [ghammad/pyActigraphy#126]
Hello,

Can I use PyActigraphy for reading ACTILIFE data?

Thank you!

**Comment by ghammad** [comment]
Hello @loukasilias 

If you are talking about Actigraph Corp's Actilife software, used to extract data from Actigraph devices (e.g. wGT3X or GTX9 devices), yes it is possible.

pyActigraphy reads Actigraph's .agd files that you can easily create with Actilife by exporting the data extracted from your device. In the pyActigraphy [tutorials](https://ghammad.github.io/pyActigraphy/tutorials.html), just replace the reader function used as an example (e.g "read_raw_awd") by the one for Actigraph data files: "read_raw_agd". More info on this function [here](https://ghammad.github.io/pyActigraphy/_autosummary/pyActigraphy.io.read_raw_agd.html#pyActigraphy.io.read_raw_agd).

Hope that helps.

Greg

**Comment by ghammad** [comment]
@loukasilias any update? Did you manage to read .agd files data with pyActigraphy?

**Comment by ghammad** [comment]
Hello @loukasilias 

I hope you managed to read your files.

Closing the issue now but feel free to re-open it.

Cheers,

Greg
