### ISSUE TITLE
ValueError: Attempting to read a metadata file referring to another input file.

### ISSUE THREAD

**Issue by Rui127** [ghammad/pyActigraphy#151]
Hi,
I am using pyActigraphy.io.read_raw_bba to read xxx-timeSeries.csv.gz file processed by biobankAccelerometer analysis (original bin file from Geneactive) and I got the errors below and seems like a name matching problem?
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 raw = pyActigraphy.io.read_raw_bba('[/Users/zhangr7/Desktop/test-timeSeries.csv.gz](http://localhost:8888/Desktop/test-timeSeries.csv.gz)')

File [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyActigraphy/io/bba/bba.py:393](http://localhost:8888/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyActigraphy/io/bba/bba.py#line=392), in read_raw_bba(input_fname, name, uuid, frequency, start_time, period, engine, impute_missing, use_metadata_json, metadata_fname)
    331 def read_raw_bba(
    332     input_fname,
    333     name=None,
   (...)
    341     metadata_fname=None
    342 ):
    343     r"""Reader function for files produced by the biobankAccelerometerAnalysis
    344     package.
    345 
   (...)
    390         An object containing preprocessed data from raw accelerometers.
    391     """
--> 393     return RawBBA(
    394         input_fname=input_fname,
    395         name=name,
    396         uuid=uuid,
    397         frequency=frequency,
    398         start_time=start_time,
    399         period=period,
    400         engine=engine,
    401         impute_missing=impute_missing,
    402         use_metadata_json=use_metadata_json,
    403         metadata_fname=metadata_fname
    404     )

File [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyActigraphy/io/bba/bba.py:87](http://localhost:8888/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyActigraphy/io/bba/bba.py#line=86), in RawBBA.__init__(self, input_fname, name, uuid, frequency, start_time, period, engine, impute_missing, use_metadata_json, metadata_fname)
     85 # read meta-data file (if found):
     86 if use_metadata_json:
---> 87     meta_data = self.__read_baa_metadata_json(
     88         input_fname, metadata_fname
     89     )
     91     # extract UUID if not provided
     92     if uuid is None:

File [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyActigraphy/io/bba/bba.py:292](http://localhost:8888/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pyActigraphy/io/bba/bba.py#line=291), in RawBBA.__read_baa_metadata_json(input_fname, metadata_fname)
    283     raise ValueError(
    284         'Could extract file basename (XXX-timeSeries.csv.gz)'
    285         + ' from input filename: {}'.format(input_fname)
    286     )
    288 if not re.match(
    289     pattern=r'{}.(cwa|CWA)(\.gz)?'.format(input_basename),
    290     string=os.path.basename(meta_data['file-name'])
    291 ):
--> 292     raise ValueError(
    293         'Attempting to read a metadata file referring to another '
    294         + 'input file.\n'
    295         + '- Input file: {}\n'.format(os.path.basename(input_fname))
    296         + '- Extracted basename: {}\n'.format(input_basename)
    297         + '- Metadata ref: {}\n'.format(
    298             os.path.basename(meta_data['file-name'])
    299         )
    300         + '- Metadata path: {}\n'.format(input_metadata)
    301     )
    302 return meta_data

ValueError: Attempting to read a metadata file referring to another input file.
- Input file: test-timeSeries.csv.gz
- Extracted basename: test
- Metadata ref: test.bin
- Metadata path: [/Users/zhangr7/Desktop/test-summary.json](http://localhost:8888/Desktop/test-summary.json)

**Comment by ghammad** [comment]
Hello @Rui127 

I just crafted a new release (v1.2.2) with a fix for this issue.

Please let me know if you still encounter any issue.

Thanks for using pyActigraphy.

Happy actigraphing.

Grégory

**Comment by Rui127** [comment]
@ghammad Hi, thank you for fixing the problem and it can read the file now. 
I am interested in using the pylight. I noticed that pyActigraphy.io.read_raw_bba('test-timeSeries.csv.gz') did not extract the light column and raw.light command is not working in this case. Are there any solutions?

raw.data.head()
time
2018-04-27 12:42:17.500000+01:00    68.219
2018-04-27 12:42:47.500000+01:00    45.655
2018-04-27 12:43:17.500000+01:00    50.365
2018-04-27 12:43:47.500000+01:00    14.811
2018-04-27 12:44:17.500000+01:00    27.244
Freq: 30s, Name: acc, dtype: float64

**Comment by Rui127** [comment]
@ghammad Thank you for fixing it and it works now
