### ISSUE TITLE
Easier install developer version

### ISSUE THREAD

**Issue by lara-roe** [ghammad/pyActigraphy#59]
Hi Gregory,

I'd suggest you change the readme instruction for installing the developer version to simply read:

`pip install https://github.com/ghammad/pyActigraphy/archive/develop.zip`

This worked better for me!

**Comment by ghammad** [comment]
Hi Lara,

thank you for the suggestion.

If possible, could you let me know what did not work with the current instructions?

I might end up proposing both methods.

Cheers,

Greg

**Comment by lara-roe** [comment]
Hi Greg,

See the screenshot below!

Best,

Lara


Am Fr., 16. Okt. 2020 um 13:09 Uhr schrieb Grégory Hammad <
notifications@github.com>:

**Comment by ghammad** [comment]
@lara-roe ...sorry but I do not see any screenshot...

**Comment by ghammad** [comment]
Ok. I got it: if you do not log in, you cannot use the ssh protocol to clone the repository. I'll add the procedure for "anonymous users" on Github.

Thank you for the info.
