### ISSUE TITLE
Support for .gt3x files?

### ISSUE THREAD

**Issue by cosmicnet** [ghammad/pyActigraphy#74]
Hello Grégory,

I have a number of .gt3x files that I'm working with. I can see from your API and documentation that this package requires .agd files. Are there any plans to add .gt3x file support? Or is there something missing from these files that makes them unsuitable?

**Comment by ghammad** [comment]
Hello @cosmicnet,

closing this issue now but feel free to re-open it if necessary and/or get in touch if you have code contributions to pyActigraphy.

Cheers,

Greg
