### ISSUE TITLE
using AW5 files

### ISSUE THREAD

**Issue by nataliepandher** [ghammad/pyActigraphy#85]
Hi, 
It says in the readme that this package is compatible with Actiwatch Spectrum plus, but how can I use the code to read AW5 files? 

Thanks!

**Comment by ghammad** [comment]
Hello @nataliepandher 

the pyActigraphy package can read various file formats (including Respironics' Actiwatch).

If your files are from Actiwatch Spectrum, you can read them with the corresponding reader function: https://ghammad.github.io/pyActigraphy/_autosummary/pyActigraphy.io.read_raw_rpx.html#pyActigraphy.io.read_raw_rpx

Let me know if it works.

Best regards,

Grégory

**Comment by nataliepandher** [comment]
Hi @ghammad 

Yes that reader function did work! Thanks so much for your help!

Happy Holidays,

Natalie
