### ISSUE TITLE
Roenneberg Algorithm (MASDA) default settings check

### ISSUE THREAD

**Issue by annambiller** [ghammad/pyActigraphy#87]
Dear Grégory, 

as discussed yesterday, here is the reminder to double check the Roenneberg (MASDA) default settings in the paper with your implemented code and whether the MASDA is always binned into 10 min.

Additionally, it would be good to i) match the description of the settings in Chrono sapiens / the Roenneberg paper with your setting names (3 bins above/below threshold and so on) so the reader is sure to match the two settings accordingly, and ii) write a note about the bin size and that you specify minutes instead.

Thanks! Anna

**Comment by ghammad** [comment]
Hello @annambiller 

Thank you for opening this issue.

As you know, the MASDA algorithm has been validated for actigraphy data aggregated into 10-min bins. I'll put a warning in the documentation about that.
Concerning the settings of the MASDA, provided that one uses 10-min bins, it was correct except for the criterium defining how to end sleep; the number of correlation values below the potential r_max. The paper states "more than three" while the current implementation is "equal to or more than three".
Taking this opportunity to look at the MASDA code, I also changed the type of this parameter. It was a number (an integer, default=3) of points and now I turned it into a duration (str, default="30min"). In case of 10-min bins, it is equivalent but it will now allow users to experiment with other bin lengths while keeping the MASDA algorithm settings identical.
```python
    r_consec_below : str, optional
        Time range to consider, past the potential correlation peak when
        searching for the maximum correlation peak.
        Default is '30Min'.
```
Finally, concerning the parameter names, I tried to match the description in the paper. But, as far as I know, the ChronoSapiens software is closed-source and I don't have access to it. Therefore, I do not know how they are presented to the users via this software.

Let me know what you think.

Regards,

Grégory

**Comment by ghammad** [comment]
Hello @annambiller 

Just to let you know; I just added the possibility to resample the data before running the MASDA algorithm. It is now easier to run the MASDA algorithm with the sampling frequency used in the validation paper (i.e. 10 min).
However, whatever the resampling frequency used, the scoring is returned with the original sampling frequency in order to ease subsequent comparison/plotting/etc.

Feel free to reopen this issue if needed.

Cheers,

Greg
