### ISSUE TITLE
M10/L5 onset

### ISSUE THREAD

**Issue by roryos1** [ghammad/pyActigraphy#89]
Hi @ghammad,

I have seen this issue has already been posted but just wanted to make sure you had seen. I was wondering whether pyActigraphy is able to calculate M10/L5 onset times. I cannot see this function in: [https://ghammad.github.io/pyActigraphy/MetricsMixin.html#pyActigraphy.metrics.MetricsMixin]. Since the code can already calculate the average activity in the L5/M10 periods, would it be possible to identify the time corresponding to the first activity data point included in the L5/M10? Although I appreciate this may be easier said than done.

Thanks, and sorry for double-posting this issue.

Rory

**Comment by ghammad** [comment]
Hello @roryos1 

thank you for the reminder.

This issue has been answered in #84 

Cheers,

Greg

**Comment by ghammad** [comment]
Closing this issue now. Feel free to re-open it if needed.
